canfdtest: Add message length support
linux-can/can-utils pull request #368
Opened 2022-06-27 16:36 UTC by RICCIARDI-Adrien

Added the '-s' command line option to set the frame payload length in bytes.

2022-06-27 20:10 UTC, marckleinebudde requested changes
looks good, just a coding style nitpick.

2022-06-27 20:10 UTC, marckleinebudde commented on canfdtest.c
> +	else {
Nitpick: please use kernel coding style:
`} else {`

2022-06-27 21:50 UTC, RICCIARDI-Adrien commented on canfdtest.c
> +	else {
Oops, sorry !

2022-06-28 08:50 UTC, marckleinebudde approved these changes

2022-06-28 08:50 UTC, merged

2022-06-30 07:30 UTC, gibsson commented
Sorry I didn't have time to dig more into the issue but one of the patch from Adrien breaks the Android build:
```
external/can-utils/lib.c:575:28: error: comparison of integers of different signs: 'int' and 'unsigned long' [-Werror,-Wsign-compare]
                                if (tmp_n < 0 || tmp_n >= len - n){
                                                 ~~~~~ ^  ~~~~~~~
external/can-utils/lib.c:581:27: error: comparison of integers of different signs: 'int' and 'unsigned long' [-Werror,-Wsign-compare]
                        if (tmp_n < 0 || tmp_n >= len - n){
                                         ~~~~~ ^  ~~~~~~~
external/can-utils/lib.c:661:28: error: comparison of integers of different signs: 'int' and 'unsigned long' [-Werror,-Wsign-compare]
                                if (tmp_n < 0 || tmp_n >= len - n){
                                                 ~~~~~ ^  ~~~~~~~
external/can-utils/lib.c:667:27: error: comparison of integers of different signs: 'int' and 'unsigned long' [-Werror,-Wsign-compare]
                        if (tmp_n < 0 || tmp_n >= len - n){
                                         ~~~~~ ^  ~~~~~~~
4 errors generated.
```

2022-06-30 07:32 UTC, gibsson commented
Oops, my jenkins logs weren't correct, it's not this pull-request but this patch that is the issue:
https://github.com/linux-can/can-utils/commit/ef853f555379babc121b90af4e8d2427aef7f2d3
Sorry for the noise Adrien ;)

2022-06-30 07:38 UTC, marckleinebudde commented
That issue was introduced in PR https://github.com/linux-can/can-utils/pull/321.

@weichslgartner, can you create patches to fix the issue?

2022-06-30 07:43 UTC, marckleinebudde commented
I've opened a new issue