canlogserver: Exit when signaled
linux-can/can-utils pull request #423
Opened 2023-04-06 09:54 UTC by yashi

With f45de1b782c083, we've removed unsafe function exit(3) from the signal handler.  But that made canlogserver's accept(3)ing process not exit; It unconditionally keeps running with EINTR.

Check the variable "running" when signaled and exit with an appropriate error code.

2023-04-06 10:39 UTC, hartkopp commented
this commit should be "canlogserver: fix termination after signal"

Because before that there was a proper exit of the application.
Also please add a "Fixes:" tag into the commit message.

2023-05-14 23:45 UTC, yashi commented
@hartkopp ping

2023-05-15 06:47 UTC, marckleinebudde requested changes
Please use the kernel coding style.

2023-05-15 06:47 UTC, marckleinebudde commented on canlogserver.c
> +		else if ((errno == EINTR) && !running) {
```suggestion
		} else if ((errno == EINTR) && !running) {
```

2023-05-15 06:47 UTC, marckleinebudde commented on canlogserver.c
> +			}
```suggestion
			if (signal_num)
				return 128 + signal_num;
			else
				return 1;
```

2023-05-15 06:49 UTC, marckleinebudde requested changes

2023-05-15 06:49 UTC, marckleinebudde commented on canlogserver.c
> +		else if ((errno == EINTR) && !running) {
```suggestion
		} else if ((errno == EINTR) && !running) {
```

2023-05-15 06:49 UTC, marckleinebudde commented on canlogserver.c
> +			}
```suggestion
			if (signal_num)
				return 128 + signal_num;
			else
				return 1;
```

2024-12-17 07:46 UTC, closed without merging