canbusload: Print error message when without @
linux-can/can-utils pull request #424
Opened 2023-04-06 09:55 UTC by yashi

When canbusload is executed without bit rate, it exits with an exit code of 1 and prints help, but without explaining why.  Users cannot know what was wrong.  When other errors occur, though, canbusload prints an error message along with the help.

Print an error message when bit rate is not given or "@" is not found.

2023-04-06 10:34 UTC, hartkopp commented
The topic of the commit message "canbusload: Print error message when without @" misses something ;-)

when what?

When the CAN interface is provided without bitrate.

So "canbusload: enhance error message for missing bitrate" would fit better IMO

2023-05-14 23:45 UTC, yashi commented
@hartkopp ping

2023-05-15 06:54 UTC, marckleinebudde requested changes

2023-05-15 06:54 UTC, marckleinebudde commented on canbusload.c
> +			fprintf(stderr, "CAN interface must have @ with bit rate\n");
What about giving an example:

"Specify CAN interfaces in the form <CAN interface>@<bitrate>, e.g. can0@500000"

2023-06-02 12:09 UTC, merged