J1939 vehicle position
linux-can/can-utils pull request #553
Opened 2024-08-04 13:27 UTC by olerem

This patch set provide support for the GPSD to J1939 service. I managed to make CmakeList work so far, but i still need help to make Makefile work properly too. How to manage properly gpsd dependecy, currenty i do not know.

2024-08-04 13:32 UTC, olerem commented
To make it compile libgps-dev package is required.

2024-08-04 17:10 UTC, JamesB192 commented on lib.c
I would have named it timespec_earlier, eh nits.

2024-08-04 17:14 UTC, JamesB192 commented on libj1939.c
SocketCAN failed to connect?

2024-08-05 07:58 UTC, marckleinebudde requested changes

2024-08-05 07:58 UTC, marckleinebudde commented on j1939_vehicle_position/j1939_vehicle_position_cmn.h
> +	__le16 date; /* Date in days since January 1, 1970 */
Bitfields are not Endianness safe

2024-08-05 07:58 UTC, marckleinebudde commented on j1939_vehicle_position/j1939_vehicle_position_srv.c
> +		vp2p->hdop = (uint8_t)(priv->gps_data.dop.hdop * 10);
casts not needed

2024-08-05 07:58 UTC, marckleinebudde commented on j1939_vehicle_position/j1939_vehicle_position_srv.c
> +		(struct nmea2000_sys_time_packet *)data;
cast not needed

2024-08-05 07:58 UTC, marckleinebudde commented on j1939_vehicle_position/j1939_vehicle_position_srv.c
> +	clock_gettime(CLOCK_REALTIME, &ts);
error handling

2024-08-05 09:21 UTC, marckleinebudde commented
> To make it compile libgps-dev package is required.

We need a cmake option for this.

2024-08-05 09:21 UTC, marckleinebudde commented
https://github.com/marckleinebudde/can-utils/actions/runs/10246077261/job/28342432051#step:4:125

I think there's a header file missing.

2024-08-05 09:22 UTC, marckleinebudde commented
Have a look for a WIP github actions fix: https://github.com/marckleinebudde/can-utils/tree/j1939_vehicle_position

2025-01-31 08:42 UTC, olerem commented
Hi all, how to proceed with this pull request?

2025-03-01 09:46 UTC, yegorich commented
Could add someething like in this patch to enable and detect GPS feature.
[gps.patch](https://github.com/user-attachments/files/19038321/gps.patch)

2025-03-01 13:17 UTC, marckleinebudde commented
> Could add someething like in this patch to enable and detect GPS feature. [gps.patch](https://github.com/user-attachments/files/19038321/gps.patch)

Seems to work now. Thank @yegorich.

The ubuntu CI is having some problems, but I don't understand why. Debian builds native, cross to armhf and arm64 with libgps and mips without libgps.

I think we can merge this now.

2025-03-01 15:24 UTC, yegorich commented
Looks like it was a temporary problem.

2025-03-01 15:48 UTC, marckleinebudde commented
No, `armhf` and `arm64` live in a different URL...still working on it.

2025-03-01 21:34 UTC, marckleinebudde commented
The packages for Debian `unstable` and `experimental` are not available in the same version for all archs. This is a temporary failure. But it's working on rolling Ubuntu and Debian `testing`. 👯‍♂️

2025-03-01 22:00 UTC, yegorich commented
Yes, there are two Multiarch issues: https://tracker.debian.org/pkg/glibc

2025-03-01 22:02 UTC, marckleinebudde commented
Thanks for looking that up. Merge anyways?

2025-03-01 22:07 UTC, yegorich commented
I'd say, yes.

2025-03-01 22:15 UTC, marckleinebudde approved these changes

2025-03-02 16:19 UTC, merged